FROM ubuntu:16.04

#setup app folder
WORKDIR /app

#make configuration folder
RUN mkdir /config

#install packages
RUN apt-get update && apt-get -y install \
    build-essential \
    curl \
    software-properties-common \
    libgeos-dev \
    python3-software-properties \
    python3-setuptools \
&& rm -rf /var/lib/apt/lists/*

#Setup python3
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1 \
&& easy_install3 pip

# Configure the application
ADD config/requirements.txt /config
RUN pip install -r /config/requirements.txt

# Copy the app folder
COPY app/ ./

# Copy the app config
ADD config/cfg.ini /app
