FROM ubuntu:16.04

#setup app folder
WORKDIR /app
COPY app/ ./

#install packages
RUN apt-get update && apt-get -y install apt-utils build-essential wget

#Instal miniconda
RUN wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN bash Miniconda3-latest-Linux-x86_64.sh -p /app/miniconda -b
RUN rm Miniconda3-latest-Linux-x86_64.sh
ENV PATH=/app/miniconda/bin:${PATH}
RUN conda update -y conda

#Create the environment
RUN conda install anaconda-client
RUN chmod u+x create_env.sh
RUN ./create_env.sh
RUN rm create_env.sh

#Initialise startup script
RUN chmod u+x exec.sh

CMD ["./exec.sh"]