# docker run -it geonode/geoserver:latest /bin/bash
# docker restart geoserver -it /bin/bash

# base image: https://hub.docker.com/_/tomcat/
FROM tomcat:8.5-jre8

#Install geoserver
RUN apt-get update && apt-get -y install unzip
RUN wget -q https://sourceforge.net/projects/geoserver/files/GeoServer/2.11.2/geoserver-2.11.2-war.zip -O /tmp/geoserver.zip
RUN unzip -q /tmp/geoserver.zip -d /tmp
RUN mv /tmp/geoserver.war /usr/local/tomcat/webapps/geoserver.war
RUN rm -f /tmp/geoserver.zip

CMD ["catalina.sh", "run"]
