
# this builds a web server!

FROM ubuntu:16.04

RUN apt-get update && apt-get -y install apt-utils python python-setuptools python-dev build-essential

# LOAD TESTING
RUN apt-get -y install stress-ng

RUN mkdir /mnt/state

WORKDIR /app

COPY app/* ./

RUN chmod u+x exec.sh

CMD ["./exec.sh"]